### ISSUE TITLE
API definition changed or variation in setup

### ISSUE THREAD

**Issue by M10tech** [galadril/Domoticz-Quatt-Plugin#1]
Hi,

I've used your plugin and found that it is not 100% fitting the output of my June2024 Quatt installation.
The 'flowMeter' section has a different payload and some other issues I've found.

My quatt has no external flowmeter but an internal one. It does connect an external temperature sensor to the CiC.

The question is if this API output is uniform for all new CiC software (v2.17.0) or if it depends on the deployment.
Some logic to select which mode is supported could be beneficial if that would be the case.

Waiting for others to report on their recent readings and see what's up.

```{
  "boiler": {
    "oTtbTurnOnOffBoilerOn": false,
    "otFbChModeActive": null,
    "otFbDhwActive": null,
    "otFbFlameOn": null,
    "otFbSupplyInletTemperature": null,
    "otFbSupplyOutletTemperature": null,
    "otTbCH": false
  },
  "flowMeter": {
    "waterSupplyTemperature": 22.404352
  },
  "hp1": {
    "getMainWorkingMode": 0,
    "limitedByCop": false,
    "modbusSlaveId": 1,
    "power": 0,
    "powerInput": 5.150232,
    "silentModeStatus": false,
    "temperatureOutside": 18.19,
    "temperatureWaterIn": 18.29,
    "temperatureWaterOut": 19.52
  },
  "qc": {
    "flowRateFiltered": 0,
    "stickyPumpProtectionEnabled": false,
    "supervisoryControlMode": 0
  },
  "system": {
    "hostName": "CIC-<UUID>"
  },
  "thermostat": {
    "otFtChEnabled": false,
    "otFtControlSetpoint": 0,
    "otFtCoolingEnabled": false,
    "otFtDhwEnabled": true,
    "otFtRoomSetpoint": 20,
    "otFtRoomTemperature": 21.40625
  },
  "time": {
    "ts": 1720186433919,
    "tsHuman": "2024-07-05T13:33:53Z"
  }
}
```

**Comment by galadril** [comment]
Mm i see. Mine actually also changed.
They removed flowRate from the flowMeter and moved it to flowRateFiltered

**Comment by galadril** [comment]
I already added the new flowMeter, but didnt notice that the old one was removed.. ill remove it from the script
https://github.com/galadril/Domoticz-Quatt-Plugin/commit/747c18a5569ae125102e655d20d7a2e839fa057f

**Comment by galadril** [comment]
Added more device in the new version 
![image](https://github.com/galadril/Domoticz-Quatt-Plugin/assets/14561640/af425b0c-86d8-41f5-8eeb-795a2a2bb0ff)

**Comment by galadril** [comment]
I closed this issue, i guess this is fixed now right
