### ISSUE TITLE
non functioning in v0.0.6

### ISSUE THREAD

**Issue by M10tech** [galadril/Domoticz-Quatt-Plugin#6]
In this release you introduced a set of processing concepts that seem not to match anything in the json

items like controlState or secondaryCircuits are unrelated to the json.

can you explain why this is supposed to work?

e.g. the qc.flowRateFiltered does not work anymore for me

**Comment by galadril** [comment]
Yeah actually the script failed to run after your PR on my machine (due to a typo on the <plugin> part), and i quickly tried to rework / fix.. while even having a different version already locally.

So i guess its now reverted and working again

**Comment by M10tech** [comment]
PR#5  was the typo I tried to fix in the last moment but you already merged PR#4 before I got to that.

Now that the dust has settled I have submitted PR#7 with some minor updates.

Sorry for the confusion and keep up the good work
